### PR TITLE
Mobile display

### PR DESCRIPTION
**Pull request by Fro99666**
some modifications for mobile compatibility
+ adding icon before title
+ fixing php notice message

### CODE REVIEW

**Comment by jrgp** [comment]
Mostly looks good, except: the theme_ CSS files are generated using sass templates.

Please take a look at layout/sass/, make your changes there to the appropriate .sass file(s), and submit the generated files that compilecss.sh makes. Take note to how the files inherit from base.sass. You probably needn't convert mobile.css to sass

Thanks!

**Comment by Fro99666** [comment]
Sorry i didn't saw you was using sass !

here comes the new changes
- mobile to sass
- icon to sass
- added compress to sass script
- added remove map to sass script

**Comment by Fro99666** [comment]
ok, i think i am done with mobile display branch ^_^

**Comment by Fro99666** [comment]
almost >_<

**Comment by jrgp** [comment]
Thanks!

**Pull request merged**
