### PR TITLE
mobile improvement

### PR DESCRIPTION
**Pull request by Fro99666**

### CODE REVIEW

**Comment by Fro99666** [comment]
i hope it is want you wanted :P

**Comment by jrgp** [comment]
This is my concern. If you look at your copy of linfo here, https://github.com/Fro99666/linfo it says it is 4 commits behind my master. I think some of the changes in this pull request are already present. Can you get your master in sync with my master?

**Comment by jrgp** [comment]
nvm I wasn't reading the right file.

**Comment by Fro99666** [comment]
so all is alright ? i am not enought familiar with git to understand all subtilities

**Comment by jrgp** [comment]
yeah we're good

**Pull request merged**
