### PR TITLE
Hyper-V - icons.css

### PR DESCRIPTION
**Pull request by Shark-kun**
added .icon_vm_hyper-v{background-image:url("icons/vm_hyper-v.png");width:16px} to display pictures (icons) for https://github.com/jrgp/linfo/commit/00ab6bbe6436dc0712779ea6a190451025022d4c

### CODE REVIEW

**Comment by jrgp** [comment]
Thanks. Would you be able to add this to `layout/sass/icons.sass`?

This way when icons.css gets auto generated again this new class will be present.

**Comment by Shark-kun** [comment]
yes, it will be visible icon, screenshot for clarity
hyper-v

**Comment by jrgp** [comment]
Hey,

I can't merge this until you update the sass file. The icons.css file is generated automatically from the contents of icons.sass

**Comment by Shark-kun** [comment]
Hi!
I hope now everything is done correctly

**Pull request merged**
