### PR TITLE
Add linux mint

### PR DESCRIPTION
**Pull request by matriphe**
Linux Mint is Debian/Ubuntu variant and can be detected by Linfo, but missing the icon.

### CODE REVIEW

**Comment by jrgp** [comment]
Can you resolve the conflicts?

**Comment by matriphe** [comment]
@jrgp ooppss.. wait, let me check it..

**Comment by jrgp** [comment]
It still isn't mergeable :(

**Comment by matriphe** [comment]
can you help me to show where's the conflict is? 🤔

**Comment by jrgp** [comment]
nvm. merged :)

**Comment by matriphe** [comment]
Fiuhh! Glad it's been solved!

**Pull request merged**
