### PR TITLE
Windows.php changes

### PR DESCRIPTION
**Pull request by ksandell**

### CODE REVIEW

**Comment by ksandell** [comment]
Travis fails PHP 5.5 because of other reasons, not the code.

**Comment by ksandell** [comment]
Hi Joe,
 
For some reason I cant see the commits merged properly into the Master. My github says I’m 1 commit behind/head all the time .. and when I pull the latest 4.0.2 I get the old source code from your repo.
 
Maybe you need to do a new release from the master branch (4.0.3) so the changes are seen by composer?
 
 
Regards,
Kim Sandell

**Comment by ksandell** [comment]
And I forgot to say, the PHP 5.5 CI pipeline always fails because travis cant download PHP 5.5. Maybe this also affects the end results.
 
-Kim

**Comment by jrgp** [comment]
Just released 4.0.3 that has your windows changes

**Comment by ksandell** [comment]
There is some discrepancy somewhere as packagist (Composer) doesnt see 4.0.3. See https://packagist.org/packages/linfo/linfo

**Pull request merged**
