### PR TITLE
Update standalone_autoload.php

### PR DESCRIPTION
**Pull request by Gummibeer**
use the `DIRECTORY_SEPARATOR` constant for cross os compatibility.

### CODE REVIEW

**Comment by jrgp** [comment]
That's not really true as "/" is converted to "\" on windows

**Comment by Gummibeer** [comment]
In wich Version? My Windows Server had notice me that he can't find the file with "/". :?

**Comment by jrgp** [comment]
Hmmm.  Does this pull request fix the entire issue ? If you're getting a specific error message in a specific spot would you be able to paste ? :)

**Comment by Gummibeer** [comment]
Wasn't specific with this package but with paths that use / and not \ it could be that some webservers correct this themself but I think the correct and right way is to use the constant!? To be sure that it will work everywhere.

**Comment by jrgp** [comment]
It's not the webserver, it's php itself. PHP internally does path translation on Windows to use \ instead of / in paths. Look at this comment: http://php.net/manual/en/dir.constants.php#113236

Furthermore, Linfo does do several path checks using forward slashes for things such as icons and themes, and it has always used forward slashes for those paths and those have always worked on windows.

**Comment by jrgp** [comment]
By the way, I'm really sorry if I came off as rude here. I appreciate your work on Linfo :)

**Pull request closed without merging**
